[workspace]
resolver = "2"
members = ["core/*", "ffi/coproduct-ffi-frb", "ffi/coproduct-ffi-uniffi"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.95.0"

[workspace.dependencies]
async-trait = "0.1.89"
flutter_rust_bridge = "2.12.0"
http = "1.3"
parking_lot = "0.12"
semver = { version = "1.0", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", default-features = false, features = ["std", "raw_value"] }
sha2 = "0.11.0"
thiserror = "2.0.18"
time = { version = "0.3", default-features = false, features = ["std", "formatting", "parsing"] }
tracing = { version = "0.1", default-features = false }
uniffi = { version = "0.31.1", features = ["cli"] }
uuid = { version = "1", default-features = false, features = ["v4"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
