// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core_header`, `from_core_method`, `from_core_request`, `to_core_header`, `to_core_response`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ObserverAdapter`, `ObserverError`, `SecureStoreAdapter`, `TransportAdapter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `on_change_bool`, `read`, `request`, `write`

Future<CoproductClientHandle> initialize({
  required String sdkKey,
  required String cacheDir,
  required FutureOr<HttpResponse> Function(HttpRequest) transportRequest,
  required FutureOr<String?> Function(String) secureRead,
  required FutureOr<void> Function(String, String) secureWrite,
}) => RustLib.instance.api.crateApiInitialize(
  sdkKey: sdkKey,
  cacheDir: cacheDir,
  transportRequest: transportRequest,
  secureRead: secureRead,
  secureWrite: secureWrite,
);

bool getBool({
  required CoproductClientHandle client,
  required String key,
  required bool defaultValue,
}) => RustLib.instance.api.crateApiGetBool(
  client: client,
  key: key,
  defaultValue: defaultValue,
);

bool wasLoadedFromCache({required CoproductClientHandle client}) =>
    RustLib.instance.api.crateApiWasLoadedFromCache(client: client);

Future<SubscriptionHandle> observe({
  required CoproductClientHandle client,
  required String key,
  required FutureOr<void> Function(bool) onChange,
}) => RustLib.instance.api.crateApiObserve(
  client: client,
  key: key,
  onChange: onChange,
);

Future<void> simulateChange({
  required CoproductClientHandle client,
  required String key,
  required bool newValue,
}) => RustLib.instance.api.crateApiSimulateChange(
  client: client,
  key: key,
  newValue: newValue,
);

int computeBucket({
  required String ruleId,
  required String targetingKey,
  required String suffix,
}) => RustLib.instance.api.crateApiComputeBucket(
  ruleId: ruleId,
  targetingKey: targetingKey,
  suffix: suffix,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoproductClientHandle>>
abstract class CoproductClientHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SubscriptionHandle>>
abstract class SubscriptionHandle implements RustOpaqueInterface {}

class HttpHeader {
  final String name;
  final String value;

  const HttpHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

enum HttpMethod { get_, post }

class HttpRequest {
  final HttpMethod method;
  final String url;
  final List<HttpHeader> headers;
  final Uint8List? body;

  const HttpRequest({
    required this.method,
    required this.url,
    required this.headers,
    this.body,
  });

  @override
  int get hashCode =>
      method.hashCode ^ url.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          url == other.url &&
          headers == other.headers &&
          body == other.body;
}

class HttpResponse {
  final int status;
  final Uint8List body;
  final List<HttpHeader> headers;

  const HttpResponse({
    required this.status,
    required this.body,
    required this.headers,
  });

  @override
  int get hashCode => status.hashCode ^ body.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body &&
          headers == other.headers;
}

@freezed
sealed class InitError with _$InitError implements FrbException {
  const InitError._();

  const factory InitError.invalidKeyType({required String prefix}) =
      InitError_InvalidKeyType;
  const factory InitError.malformedSdkKey({required String reason}) =
      InitError_MalformedSdkKey;
  const factory InitError.missingSdkKey() = InitError_MissingSdkKey;
  const factory InitError.invalidConfig({
    required String field,
    required String reason,
  }) = InitError_InvalidConfig;
  const factory InitError.unsupportedSchemaVersion({
    required int actual,
    required int supported,
  }) = InitError_UnsupportedSchemaVersion;
}
