// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `attach`, `close`, `from_core_header`, `from_core_method`, `from_core_request`, `into_core`, `into_core`, `record`, `register_single`, `to_core_header`, `to_core_response`, `unattached`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelObserver`, `ChannelState`, `ObserveChannel`, `ObserverError`, `SecureStoreAdapter`, `TransportAdapter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `on_close`, `on_transition`, `read`, `request`, `write`

Future<CoproductClientHandle> initialize({
  required String sdkKey,
  required String userAgent,
  required FfiConfig config,
  required String cacheDir,
  required FutureOr<HttpResponse> Function(HttpRequest) transportRequest,
  required FutureOr<String?> Function(String) secureRead,
  required FutureOr<void> Function(String, String) secureWrite,
}) => RustLib.instance.api.crateApiInitialize(
  sdkKey: sdkKey,
  userAgent: userAgent,
  config: config,
  cacheDir: cacheDir,
  transportRequest: transportRequest,
  secureRead: secureRead,
  secureWrite: secureWrite,
);

bool getBool({
  required CoproductClientHandle client,
  required String key,
  required bool defaultValue,
}) => RustLib.instance.api.crateApiGetBool(
  client: client,
  key: key,
  defaultValue: defaultValue,
);

String getString({
  required CoproductClientHandle client,
  required String key,
  required String defaultValue,
}) => RustLib.instance.api.crateApiGetString(
  client: client,
  key: key,
  defaultValue: defaultValue,
);

PlatformInt64 getInt({
  required CoproductClientHandle client,
  required String key,
  required PlatformInt64 defaultValue,
}) => RustLib.instance.api.crateApiGetInt(
  client: client,
  key: key,
  defaultValue: defaultValue,
);

double getNumber({
  required CoproductClientHandle client,
  required String key,
  required double defaultValue,
}) => RustLib.instance.api.crateApiGetNumber(
  client: client,
  key: key,
  defaultValue: defaultValue,
);

String getJson({
  required CoproductClientHandle client,
  required String key,
  required String defaultValueJson,
}) => RustLib.instance.api.crateApiGetJson(
  client: client,
  key: key,
  defaultValueJson: defaultValueJson,
);

Future<void> identify({
  required CoproductClientHandle handle,
  required String userId,
  required Map<String, FrbContextValue> attributes,
  required bool linkAnonymous,
}) => RustLib.instance.api.crateApiIdentify(
  handle: handle,
  userId: userId,
  attributes: attributes,
  linkAnonymous: linkAnonymous,
);

Future<void> signOut({required CoproductClientHandle handle}) =>
    RustLib.instance.api.crateApiSignOut(handle: handle);

Future<void> setContext({
  required CoproductClientHandle handle,
  required String targetingKey,
  required Map<String, FrbContextValue> attributes,
}) => RustLib.instance.api.crateApiSetContext(
  handle: handle,
  targetingKey: targetingKey,
  attributes: attributes,
);

Future<void> updateAttributes({
  required CoproductClientHandle handle,
  required Map<String, FrbContextValue> attributes,
}) => RustLib.instance.api.crateApiUpdateAttributes(
  handle: handle,
  attributes: attributes,
);

Future<void> removeAttributes({
  required CoproductClientHandle handle,
  required List<String> names,
}) =>
    RustLib.instance.api.crateApiRemoveAttributes(handle: handle, names: names);

Future<void> setAutoPopulatedAttributes({
  required CoproductClientHandle handle,
  required Map<String, FrbContextValue> attributes,
}) => RustLib.instance.api.crateApiSetAutoPopulatedAttributes(
  handle: handle,
  attributes: attributes,
);

String? previousAnonymousId({required CoproductClientHandle handle}) =>
    RustLib.instance.api.crateApiPreviousAnonymousId(handle: handle);

int bucketForVectors({
  required String ruleId,
  required String targetingKey,
  required String suffix,
}) => RustLib.instance.api.crateApiBucketForVectors(
  ruleId: ruleId,
  targetingKey: targetingKey,
  suffix: suffix,
);

ProviderState state({required CoproductClientHandle client}) =>
    RustLib.instance.api.crateApiState(client: client);

Future<PollOutcome> pollNow({required CoproductClientHandle client}) =>
    RustLib.instance.api.crateApiPollNow(client: client);

Future<void> shutdown({required CoproductClientHandle client}) =>
    RustLib.instance.api.crateApiShutdown(client: client);

BoolObserveSession observeBool({
  required CoproductClientHandle client,
  required String key,
}) => RustLib.instance.api.crateApiObserveBool(client: client, key: key);

bool? observeBoolSeed({required BoolObserveSession session}) =>
    RustLib.instance.api.crateApiObserveBoolSeed(session: session);

Stream<bool?> observeBoolEvents({required BoolObserveSession session}) =>
    RustLib.instance.api.crateApiObserveBoolEvents(session: session);

void cancelBoolObservation({required BoolObserveSession session}) =>
    RustLib.instance.api.crateApiCancelBoolObservation(session: session);

StringObserveSession observeString({
  required CoproductClientHandle client,
  required String key,
}) => RustLib.instance.api.crateApiObserveString(client: client, key: key);

String? observeStringSeed({required StringObserveSession session}) =>
    RustLib.instance.api.crateApiObserveStringSeed(session: session);

Stream<String?> observeStringEvents({required StringObserveSession session}) =>
    RustLib.instance.api.crateApiObserveStringEvents(session: session);

void cancelStringObservation({required StringObserveSession session}) =>
    RustLib.instance.api.crateApiCancelStringObservation(session: session);

IntObserveSession observeInt({
  required CoproductClientHandle client,
  required String key,
}) => RustLib.instance.api.crateApiObserveInt(client: client, key: key);

PlatformInt64? observeIntSeed({required IntObserveSession session}) =>
    RustLib.instance.api.crateApiObserveIntSeed(session: session);

Stream<PlatformInt64?> observeIntEvents({required IntObserveSession session}) =>
    RustLib.instance.api.crateApiObserveIntEvents(session: session);

void cancelIntObservation({required IntObserveSession session}) =>
    RustLib.instance.api.crateApiCancelIntObservation(session: session);

NumberObserveSession observeNumber({
  required CoproductClientHandle client,
  required String key,
}) => RustLib.instance.api.crateApiObserveNumber(client: client, key: key);

double? observeNumberSeed({required NumberObserveSession session}) =>
    RustLib.instance.api.crateApiObserveNumberSeed(session: session);

Stream<double?> observeNumberEvents({required NumberObserveSession session}) =>
    RustLib.instance.api.crateApiObserveNumberEvents(session: session);

void cancelNumberObservation({required NumberObserveSession session}) =>
    RustLib.instance.api.crateApiCancelNumberObservation(session: session);

JsonObserveSession observeJson({
  required CoproductClientHandle client,
  required String key,
}) => RustLib.instance.api.crateApiObserveJson(client: client, key: key);

String? observeJsonSeed({required JsonObserveSession session}) =>
    RustLib.instance.api.crateApiObserveJsonSeed(session: session);

Stream<String?> observeJsonEvents({required JsonObserveSession session}) =>
    RustLib.instance.api.crateApiObserveJsonEvents(session: session);

void cancelJsonObservation({required JsonObserveSession session}) =>
    RustLib.instance.api.crateApiCancelJsonObservation(session: session);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BoolObserveSession>>
abstract class BoolObserveSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoproductClientHandle>>
abstract class CoproductClientHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IntObserveSession>>
abstract class IntObserveSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsonObserveSession>>
abstract class JsonObserveSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NumberObserveSession>>
abstract class NumberObserveSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StringObserveSession>>
abstract class StringObserveSession implements RustOpaqueInterface {}

class FfiConfig {
  final PlatformInt64 pollIntervalUs;
  final PlatformInt64 startupTimeoutUs;
  final String? endpoint;

  const FfiConfig({
    required this.pollIntervalUs,
    required this.startupTimeoutUs,
    this.endpoint,
  });

  @override
  int get hashCode =>
      pollIntervalUs.hashCode ^ startupTimeoutUs.hashCode ^ endpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiConfig &&
          runtimeType == other.runtimeType &&
          pollIntervalUs == other.pollIntervalUs &&
          startupTimeoutUs == other.startupTimeoutUs &&
          endpoint == other.endpoint;
}

@freezed
sealed class FrbContextValue with _$FrbContextValue {
  const FrbContextValue._();

  const factory FrbContextValue.string(String field0) = FrbContextValue_String;
  const factory FrbContextValue.number(double field0) = FrbContextValue_Number;
  const factory FrbContextValue.bool(bool field0) = FrbContextValue_Bool;
  const factory FrbContextValue.stringList(List<String> field0) =
      FrbContextValue_StringList;
  const factory FrbContextValue.null_() = FrbContextValue_Null;
}

class HttpHeader {
  final String name;
  final String value;

  const HttpHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

enum HttpMethod { get_, post }

class HttpRequest {
  final HttpMethod method;
  final String url;
  final List<HttpHeader> headers;
  final Uint8List? body;

  const HttpRequest({
    required this.method,
    required this.url,
    required this.headers,
    this.body,
  });

  @override
  int get hashCode =>
      method.hashCode ^ url.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          url == other.url &&
          headers == other.headers &&
          body == other.body;
}

class HttpResponse {
  final int status;
  final Uint8List body;
  final List<HttpHeader> headers;

  const HttpResponse({
    required this.status,
    required this.body,
    required this.headers,
  });

  @override
  int get hashCode => status.hashCode ^ body.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body &&
          headers == other.headers;
}

enum IdentityError { invalidTargetingKey }

@freezed
sealed class InitError with _$InitError implements FrbException {
  const InitError._();

  const factory InitError.invalidKeyType({required String prefix}) =
      InitError_InvalidKeyType;
  const factory InitError.malformedSdkKey({required String reason}) =
      InitError_MalformedSdkKey;
  const factory InitError.missingSdkKey() = InitError_MissingSdkKey;
  const factory InitError.invalidConfig({
    required String field,
    required String reason,
  }) = InitError_InvalidConfig;
  const factory InitError.unsupportedSchemaVersion({
    required int actual,
    required int supported,
  }) = InitError_UnsupportedSchemaVersion;
}

@freezed
sealed class PollOutcome with _$PollOutcome {
  const PollOutcome._();

  const factory PollOutcome.updated() = PollOutcome_Updated;
  const factory PollOutcome.notModified() = PollOutcome_NotModified;
  const factory PollOutcome.fatal() = PollOutcome_Fatal;
  const factory PollOutcome.retrying() = PollOutcome_Retrying;
  const factory PollOutcome.rateLimited({
    required PlatformInt64 retryAfterSecs,
  }) = PollOutcome_RateLimited;
  const factory PollOutcome.stale() = PollOutcome_Stale;
  const factory PollOutcome.dedupedSkipped() = PollOutcome_DedupedSkipped;
}

enum ProviderState { notReady, ready, reconciling, retrying, stale, fatal }
