#!/usr/bin/env bash
set -euo pipefail

# Builds a self-contained Swift Package fixture at build/ios-spm/ that the
# iOS consumer-test app can consume as a local SwiftPM dependency. The fixture
# simulates what a published release would look like from the consumer's
# perspective: a Package.swift declaring a binary target backed by the
# locally-produced xcframework zip, plus a vendored snapshot of the wrapper
# Swift source from sdks/ios/Sources/Coproduct/.
#
# This is a release-shape simulation, not a true release flow. Apple requires
# binary-target URLs to be https://, so the fixture uses .binaryTarget(path:)
# against the local zip rather than .binaryTarget(url:, checksum:). The
# URL+checksum download path gets exercised once a real GitHub release URL
# exists, which is a separate workstream

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
output_dir="$repo_root/build/ios-spm"
wrapper_source_dir="$repo_root/sdks/ios/Sources/Coproduct"
ffi_source_dir="$repo_root/sdks/ios/Sources/CoproductFFI"

# Step 1: produce the binary artifact (zip + checksum). This wipes and
# repopulates $output_dir, so any prior fixture state is discarded
"$repo_root/scripts/package/ios-spm-binary.sh"

# Step 2: vendor the wrapper Swift source into the fixture. SwiftPM requires
# a target's source to live inside the package's own directory tree, so we
# copy rather than reference sdks/ios/Sources/ directly. The generated bindings
# live in their own CoproductFFI target that is not a product, mirroring the
# real package so the consumer can only reach the wrapper's public surface
mkdir -p "$output_dir/Sources"
cp -R "$wrapper_source_dir" "$output_dir/Sources/Coproduct"
cp -R "$ffi_source_dir" "$output_dir/Sources/CoproductFFI"

# Step 3: emit the fixture's Package.swift. The binary target's name and
# language-mode settings match sdks/ios/Package.swift so the wrapper source
# compiles identically against the fixture's vendored copy of itself
cat > "$output_dir/Package.swift" <<'SWIFT'
// swift-tools-version: 6.3
// Generated by scripts/package/ios-spm-fixture.sh. Do not edit by hand.
// Re-run the script to refresh.

import PackageDescription

let package = Package(
    name: "Coproduct",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "Coproduct",
            targets: ["Coproduct"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "coproduct_ffi_uniffiFFI",
            path: "CoproductFFI.xcframework.zip"
        ),
        .target(
            name: "CoproductFFI",
            dependencies: ["coproduct_ffi_uniffiFFI"]
        ),
        .target(
            name: "Coproduct",
            dependencies: ["CoproductFFI"]
        ),
    ],
    swiftLanguageModes: [.v5]
)
SWIFT

echo
echo "Fixture written to $output_dir"
echo "Layout:"
(cd "$output_dir" && find . -maxdepth 4 -not -path '*/\.*' | sort)
