// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-coproduct.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "CoproductSpec.h"

@interface Coproduct : NSObject <NativeCoproductSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Coproduct : NSObject <RCTBridgeModule>
#endif

@end